version: '3.5'

services:
  backend:
    depends_on: 
    - "mongo"
    container_name: scale_backend
    image: node:alpine
    command: 'npm run backend'
    working_dir: '/data'
    volumes:
      - ./:/data
    ports:
      - "9000:9000"
    networks:
      - back
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: volume
        source: scale-vol
        target: /data/db
    ports:
      - "27017:27017"
    command: 'mongod --auth --dbpath /data/db'
    restart: always
    networks:
      - back
  mongo-express:
    depends_on: 
    - "mongo"
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    restart: always
    
volumes:
  scale-vol:
    external: true
  backend-vol:

networks:
  back:

    