const constants = {
    VALIDATE_SCALE: 'VALIDATE_SCALE',
    NEW_SCALE: 'NEW_SCALE',
    ATTEMPT_NOTE: 'ATTEMPT_NOTE',
    SET_POSITION: 'SET_POSITION',
    FIND_NEW_POSITION: 'FIND_NEW_POSITION'
}

export default constants;